name: Generate web tokens

on:
  release:
    types: [created]

jobs:
  Run_tokens_transformer_and_push_generated_files:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Transform tokens
        run: npx token-transformer tokens.json output-tokens.json --excludes '$themes' --excludes '$metadata' --sets component/light --sets component/dark --sets alias --sets global

      - name: Generate Tokens for Kotlin and Swift
        run: node index.js ./output-tokens.json theme-data.js
  
      - name: Push to Fiber-web
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        working-directory: ${{ github.workspace }} 
        run: |
          git config --global user.name 'peter1Osama'
          git config --global user.email 'peter.badrous@btech.com'
          git clone https://user:$ACCESS_TOKEN@github.com:peter1Osama/web-core-config-public.git fiber-web-temp
          rm -rf fiber-ios-temp/web-core-config-public/theme-data.js
          cp theme-data.js fiber-web-temp/web-core-config-public
          cd fiber-web-temp
          git add .
          git commit -m "Copy theme-data.js from fiber-core"
          git push origin main
